// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using DBFirst.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DBFirst.Models
{
    public partial interface INorthwindContextProcedures
    {
        Task<List<SalesByCategoryResult>> SalesByCategoryAsync(string? categoryName, string? ordYear, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SelectAllCategoriesResult>> SelectAllCategoriesAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
    }
}
